spring:
  application:
    name: gateway-service

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:broker:9092}
    consumer:
      group-id: ${SPRING_KAFKA_CONSUMER_GROUP_ID:gateway}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
      auto-offset-reset: earliest
    producer:
      client-id: gateway-producer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  security:
    user:
      name: ${ACTUATOR_USER:admin}
      password: ${ACTUATOR_PASSWORD:admin123}

server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful
  tomcat:
    threads:
      max: 200
      min-spare: 10
    connection-timeout: 20000
    max-connections: 10000
    accept-count: 100

logging:
  level:
    by.parakhnevich.gateway: ${LOG_LEVEL:DEBUG}
    org.springframework.web: INFO
    org.springframework.security: WARN
    org.springframework.kafka: INFO
#    org.springframework.kafka: TRACE
#    org.springframework.kafka.listener: TRACE
  pattern:
    console: "%d{ISO8601} %highlight(%-5level) [%thread] %logger{36} - %msg%n"
    file: "%d{ISO8601} %-5level [%thread] %logger{36} - %msg%n"
  file:
    name: /var/log/gateway-service/app.log
    max-size: 100MB
    max-history: 30