CREATE TABLE bands (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(40) NOT NULL,
    description varchar(255),
    geo         varchar(40),
    image_url   varchar(40),
    created_at  timestamp(6) NOT NULL DEFAULT now(),
    updated_at  timestamp(6) NOT NULL DEFAULT now(),
    CONSTRAINT bands_name_uniq UNIQUE (name)
);
CREATE INDEX idx_bands_name ON bands (name);

CREATE TABLE musicians (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(50) NOT NULL,
    image_url   varchar(40),
    birth_date  date,
    created_at  timestamp(6) NOT NULL DEFAULT now(),
    updated_at  timestamp(6) NOT NULL DEFAULT now()
);
CREATE INDEX idx_musicians_name ON musicians (name);

CREATE TABLE genres (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(40) NOT NULL,
    description varchar(255),
    created_at  timestamp(6) NOT NULL DEFAULT now(),
    updated_at  timestamp(6) NOT NULL DEFAULT now(),
    CONSTRAINT genres_name_uniq UNIQUE (name)
);

CREATE TABLE tracks (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       varchar(255) NOT NULL,
    duration    int4,
    track_path   text,
    created_at  timestamp(6) NOT NULL DEFAULT now(),
    updated_at  timestamp(6) NOT NULL DEFAULT now(),
    CONSTRAINT tracks_duration_positive CHECK (duration IS NULL OR duration > 0),
    CONSTRAINT tracks_trackpath_uniq UNIQUE (trackpath)
);
CREATE INDEX idx_tracks_title ON tracks (title);

CREATE TABLE collections (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          varchar(40) NOT NULL,
    description    varchar(255),
	collection_type varchar(40) NULL,
	image_url   varchar(40),
    created_at     timestamp(6) NOT NULL DEFAULT now(),
    updated_at     timestamp(6) NOT NULL DEFAULT now()
);


CREATE TABLE band_genre (
    band_id  bigint NOT NULL,
    genre_id bigint NOT NULL,
    PRIMARY KEY (band_id, genre_id),
    CONSTRAINT fk_band_genre_band
        FOREIGN KEY (band_id)  REFERENCES bands(id)  ON DELETE CASCADE,
    CONSTRAINT fk_band_genre_genre
        FOREIGN KEY (genre_id) REFERENCES genres(id) ON DELETE CASCADE
);
CREATE INDEX idx_band_genre_genre ON band_genre (genre_id);

CREATE TABLE band_musician (
    band_id     bigint NOT NULL,
    musician_id bigint NOT NULL,
    PRIMARY KEY (band_id, musician_id),
    CONSTRAINT fk_band_musician_band
        FOREIGN KEY (band_id)     REFERENCES bands(id)     ON DELETE CASCADE,
    CONSTRAINT fk_band_musician_musician
        FOREIGN KEY (musician_id) REFERENCES musicians(id) ON DELETE CASCADE
);
CREATE INDEX idx_band_musician_musician ON band_musician (musician_id);

CREATE TABLE track_band (
    band_id  bigint NOT NULL,
    track_id bigint NOT NULL,
    PRIMARY KEY (band_id, track_id),
    CONSTRAINT fk_track_band_band
        FOREIGN KEY (band_id)  REFERENCES bands(id)  ON DELETE CASCADE,
    CONSTRAINT fk_track_band_track
        FOREIGN KEY (track_id) REFERENCES tracks(id) ON DELETE CASCADE
);
CREATE INDEX idx_track_band_track ON track_band (track_id);

CREATE TABLE track_collection (
    collection_id bigint NOT NULL,
    track_id      bigint NOT NULL,
    PRIMARY KEY (collection_id, track_id),
    CONSTRAINT fk_track_collection_collection
        FOREIGN KEY (collection_id) REFERENCES collections(id) ON DELETE CASCADE,
    CONSTRAINT fk_track_collection_track
        FOREIGN KEY (track_id)      REFERENCES tracks(id)      ON DELETE CASCADE
);
CREATE INDEX idx_track_collection_track ON track_collection (track_id);

CREATE TABLE track_genre (
    genre_id bigint NOT NULL,
    track_id bigint NOT NULL,
    PRIMARY KEY (genre_id, track_id),
    CONSTRAINT fk_track_genre_genre
        FOREIGN KEY (genre_id) REFERENCES genres(id) ON DELETE CASCADE,
    CONSTRAINT fk_track_genre_track
        FOREIGN KEY (track_id) REFERENCES tracks(id) ON DELETE CASCADE
);
CREATE INDEX idx_track_genre_track ON track_genre (track_id);