plugins {
    id 'java'
    id 'io.quarkus' version "${quarkusVersion}"
    id 'io.freefair.lombok' version "${lombokVersion}"
    id 'org.flywaydb.flyway' version "${flywayVersion}"
}

group = 'by.parakhnevich'
version = '1.0.0'

java {
    sourceCompatibility = '21'
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // Quarkus BOM
    implementation enforcedPlatform("io.quarkus.platform:quarkus-bom:${quarkusVersion}")

    implementation "io.quarkus:quarkus-rest"
    implementation "io.quarkus:quarkus-rest-jsonb"

    // Quarkus core
    implementation 'io.quarkus:quarkus-arc'
    implementation 'io.quarkus:quarkus-hibernate-orm'
    implementation 'io.quarkus:quarkus-hibernate-validator'
    implementation 'io.quarkus:quarkus-jdbc-postgresql'
    implementation "io.quarkus:quarkus-hibernate-orm-panache"
    implementation 'io.quarkus:quarkus-flyway'

    // Kafka (SmallRye Reactive Messaging)
    implementation 'io.quarkus:quarkus-messaging-kafka'

    // Security
    implementation "org.springframework.security:spring-security-crypto:${springVersion}"
    implementation("io.jsonwebtoken:jjwt:${jwtVersion}")

    // Cachegf
    implementation 'io.quarkus:quarkus-cache'

    // Jackson + JavaTime
    implementation 'io.quarkus:quarkus-jackson'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'

    // MapStruct
    implementation "org.mapstruct:mapstruct:${mapstructVersion}"
    annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"

    // Metrics & Health
    implementation 'io.quarkus:quarkus-micrometer'
    implementation 'io.quarkus:quarkus-smallrye-health'

    // Logging JSON
    implementation 'io.quarkus:quarkus-logging-json'

    // Common module (ваш общий DTO)
    implementation project(":common-dto")

    // Test
    testImplementation 'io.quarkus:quarkus-junit5'
    testImplementation 'io.quarkus:quarkus-junit5-mockito'
    testImplementation 'io.quarkus:quarkus-test-h2'
    testImplementation 'org.awaitility:awaitility:4.3.0'
    testImplementation("io.smallrye.reactive:smallrye-reactive-messaging-in-memory")
    testImplementation 'org.assertj:assertj-core:3.24.2'
}

flyway {
    url = 'jdbc:postgresql://localhost:5432/users'
    user = 'postgres'
    password = '1234'
    locations = ['filesystem:src/main/resources/db/migration']
}